services:
  acesso:
    container_name: acesso
    hostname: acesso
    image: teste:latest
    restart: always
    environment:
        - ROOT_PASSWORD=Sua_Senha_Segura
    volumes:
      - /srv/acesso:/root
    ports:
      - "19022:22"
  
