services:
  acesso:
    container_name: acesso
    hostname: acesso
    image: aprendendolinux/alpine:latest
    restart: always
    environment:
      - ROOT_PASSWORD=Sua_Senha_Segura
    volumes:
      - /srv/acesso:/root
    ports:
      - "2222:22"
